products:
    tencent:
        - namespace: QCE/BWP
          period: null
          auto_discover: true
          metric_info:
            - metric_list:
                - InTraffic
              period: null
              statistics: []
