apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default "multicloud-exporter" .Values.fullname }}
  labels: {{- include "multicloud-exporter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "multicloud-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "multicloud-exporter.selectorLabels" . | nindent 8 }}
{{- if .Values.reloader.enabled }}
      annotations:
{{- if .Values.reloader.useAuto }}
        reloader.stakater.com/auto: "true"
{{- else }}
        configmap.reloader.stakater.com/reload: "{{ default "multicloud-exporter" .Values.fullname }}-config{{- if and .Values.accounts (or .Values.accounts.secrets .Values.accounts.grouped) }},{{ default "multicloud-exporter" .Values.fullname }}-accounts{{- end }}"
{{- end }}
{{- end }}
    spec:
      containers:
        - name: exporter
          image: "{{ .Values.image.registry | default "ghcr.io/jangrui" }}/{{ default .Chart.Name .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: EXPORTER_PORT
              value: {{ .Values.service.port | quote }}
            - name: SERVER_PATH
              value: "/app/configs/server.yaml"
{{- if and .Values.accounts (or .Values.accounts.secrets .Values.accounts.grouped) }}
            - name: ACCOUNTS_PATH
              value: "/app/configs/accounts.yaml"
{{- end }}
{{- if and .Values.accounts (.Values.accounts.grouped) }}
{{- range $i, $a := .Values.accounts.grouped.aliyun }}
            - name: ALY_ACC_{{ $i }}_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: account_id
            - name: ALY_ACC_{{ $i }}_AK
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: access_key_id
            - name: ALY_ACC_{{ $i }}_SK
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: access_key_secret
{{- end }}
{{- range $i, $a := .Values.accounts.grouped.tencent }}
            - name: TCE_ACC_{{ $i }}_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: account_id
            - name: TCE_ACC_{{ $i }}_AK
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: access_key_id
            - name: TCE_ACC_{{ $i }}_SK
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: access_key_secret
{{- end }}
{{- range $i, $a := .Values.accounts.grouped.huawei }}
            - name: HUA_ACC_{{ $i }}_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: account_id
            - name: HUA_ACC_{{ $i }}_AK
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: access_key_id
            - name: HUA_ACC_{{ $i }}_SK
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: access_key_secret
{{- end }}
{{- else if and .Values.accounts (.Values.accounts.secrets) }}
{{- range $i, $a := .Values.accounts.secrets }}
            - name: ACC_{{ $i }}_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: account_id
            - name: ACC_{{ $i }}_AK
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: access_key_id
            - name: ACC_{{ $i }}_SK
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: access_key_secret
{{- end }}
{{- end }}
          volumeMounts:
            - name: server
              mountPath: "/app/configs/server.yaml"
              subPath: server.yaml
{{- if and .Values.accounts (or .Values.accounts.secrets .Values.accounts.grouped) }}
            - name: accounts
              mountPath: "/app/configs/accounts.yaml"
              subPath: accounts.yaml
{{- end }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: server
          configMap:
            name: {{ default "multicloud-exporter" .Values.fullname }}-config
{{- if and .Values.accounts (or .Values.accounts.secrets .Values.accounts.grouped) }}
        - name: accounts
          configMap:
            name: {{ default "multicloud-exporter" .Values.fullname }}-accounts
{{- end }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
