apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default "multicloud-exporter" .Values.fullname }}
  labels: {{- include "multicloud-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "multicloud-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "multicloud-exporter.selectorLabels" . | nindent 8 }}
{{- if .Values.reloader.enabled }}
      annotations:
{{- if .Values.reloader.useAuto }}
        reloader.stakater.com/auto: "true"
{{- else }}
        configmap.reloader.stakater.com/reload: "{{ default "multicloud-exporter" .Values.fullname }}-config{{- if and .Values.accounts .Values.accounts.grouped }},{{ default "multicloud-exporter" .Values.fullname }}-accounts{{- end }}"
{{- end }}
{{- end }}
    spec:
      containers:
        - name: exporter
          image: "{{ .Values.image.registry | default "ghcr.io/jangrui" }}/{{ default .Chart.Name .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          livenessProbe:
{{- if .Values.probes.liveness.enabled }}
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
{{- end }}
          readinessProbe:
{{- if .Values.probes.readiness.enabled }}
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
{{- end }}
          env:
            - name: CLUSTER_DISCOVERY
              value: {{ .Values.cluster.discovery | quote }}
{{- if or .Values.cluster.svcName (and (eq .Values.cluster.discovery "headless") .Values.headless.enabled) }}
            - name: CLUSTER_SVC
              value: {{ .Values.cluster.svcName | default (printf "%s-headless" (default "multicloud-exporter" .Values.fullname)) | quote }}
{{- end }}
{{- if .Values.cluster.file }}
            - name: CLUSTER_FILE
              value: {{ .Values.cluster.file | quote }}
{{- end }}
{{- if .Values.cluster.sharding.enabled }}
            - name: EXPORT_SHARD_TOTAL
              value: {{ .Values.cluster.sharding.total | quote }}
            - name: EXPORT_SHARD_INDEX
              value: {{ .Values.cluster.sharding.index | quote }}
{{- end }}
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
{{- if .Values.env }}
{{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
{{- end }}
{{- end }}
{{- if .Values.server }}
            - name: SERVER_PATH
              value: "/app/configs/server.yaml"
{{- end }}
{{- if and .Values.server .Values.server.regionDiscovery .Values.server.regionDiscovery.enabled }}
            - name: REGION_DATA_DIR
              value: /app/data
{{- end }}
{{- if and .Values.accounts .Values.accounts.grouped }}
            - name: ACCOUNTS_PATH
              value: "/app/configs/accounts.yaml"
{{- range $i, $a := .Values.accounts.grouped.aliyun }}
            - name: ALY_ACC_{{ $i }}_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: account_id
            - name: ALY_ACC_{{ $i }}_AK
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: access_key_id
            - name: ALY_ACC_{{ $i }}_SK
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: access_key_secret
{{- if $a.regions }}
            - name: ALY_REGIONS_{{ $i }}
              value: {{ printf "%s" (toYaml $a.regions) | quote }}
{{- end }}
{{- if $a.resources }}
            - name: ALY_RESOURCES_{{ $i }}
              value: {{ printf "%s" (toYaml $a.resources) | quote }}
{{- end }}
{{- end }}
{{- range $i, $a := .Values.accounts.grouped.tencent }}
            - name: TCE_ACC_{{ $i }}_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: account_id
            - name: TCE_ACC_{{ $i }}_AK
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: access_key_id
            - name: TCE_ACC_{{ $i }}_SK
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: access_key_secret
{{- if $a.regions }}
            - name: TCE_REGIONS_{{ $i }}
              value: {{ printf "%s" (toYaml $a.regions) | quote }}
{{- end }}
{{- if $a.resources }}
            - name: TCE_RESOURCES_{{ $i }}
              value: {{ printf "%s" (toYaml $a.resources) | quote }}
{{- end }}
{{- end }}
{{- range $i, $a := .Values.accounts.grouped.huawei }}
            - name: HUA_ACC_{{ $i }}_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: account_id
            - name: HUA_ACC_{{ $i }}_AK
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: access_key_id
            - name: HUA_ACC_{{ $i }}_SK
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: access_key_secret
{{- if $a.regions }}
            - name: HUA_REGIONS_{{ $i }}
              value: {{ printf "%s" (toYaml $a.regions) | quote }}
{{- end }}
{{- if $a.resources }}
            - name: HUA_RESOURCES_{{ $i }}
              value: {{ printf "%s" (toYaml $a.resources) | quote }}
{{- end }}
{{- end }}
{{- range $i, $a := .Values.accounts.grouped.aws }}
            - name: AWS_ACC_{{ $i }}_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: account_id
            - name: AWS_ACC_{{ $i }}_AK
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: access_key_id
            - name: AWS_ACC_{{ $i }}_SK
              valueFrom:
                secretKeyRef:
                  name: {{ $a.name }}
                  key: access_key_secret
{{- if $a.regions }}
            - name: AWS_REGIONS_{{ $i }}
              value: {{ printf "%s" (toYaml $a.regions) | quote }}
{{- end }}
{{- if $a.resources }}
            - name: AWS_RESOURCES_{{ $i }}
              value: {{ printf "%s" (toYaml $a.resources) | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.security.adminSecretName }}
          envFrom:
            - secretRef:
                name: {{ .Values.security.adminSecretName }}
{{- end }}
          volumeMounts:
{{- if .Values.server }}
            - name: server-config
              mountPath: "/app/configs/server.yaml"
              subPath: server.yaml
{{- end }}
{{- if and .Values.accounts .Values.accounts.grouped }}
            - name: accounts
              mountPath: "/app/configs/accounts.yaml"
              subPath: accounts.yaml
{{- end }}
{{- if and .Values.server .Values.server.regionDiscovery .Values.server.regionDiscovery.enabled }}
            - name: region-data
              mountPath: /app/data
{{- end }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
      volumes:
{{- if .Values.server }}
        - name: server-config
          configMap:
            name: {{ default "multicloud-exporter" .Values.fullname }}-config
{{- end }}
{{- if and .Values.accounts .Values.accounts.grouped }}
        - name: accounts
          configMap:
            name: {{ default "multicloud-exporter" .Values.fullname }}-accounts
{{- end }}
{{- if and .Values.server .Values.server.regionDiscovery .Values.server.regionDiscovery.enabled }}
        - name: region-data
{{- if .Values.regionData.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.regionData.persistence.existingClaim | default (printf "%s-region-data" (default "multicloud-exporter" .Values.fullname)) }}
{{- else }}
          emptyDir: {}
{{- end }}
{{- end }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      topologySpreadConstraints: {{- toYaml .Values.topologySpreadConstraints | nindent 8 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
