{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ default "multicloud-exporter" .Values.fullname }}
  labels: {{- include "multicloud-exporter.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ default "multicloud-exporter" .Values.fullname }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
{{- toYaml .Values.hpa.metrics | nindent 4 }}
{{- end }}
