apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "multicloud-exporter.fullname" . }}-products
data:
  products.yaml: |
    products:
      aliyun:
        - namespace: acs_bandwidth_package
          period: 60
          metric_info:
            - metric_list:
              - in_bandwidth_utilization
              - out_bandwidth_utilization
              - net_rx.rate
              - net_tx.rate
              - net_rx.Pkgs
              - net_tx.Pkgs
              - in_ratelimit_drop_pps
              - out_ratelimit_drop_pps
      huawei: []
      tencent: []
