{{- if and .Values.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ default "multicloud-exporter" .Values.fullname }}
  labels:
    {{- include "multicloud-exporter.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "multicloud-exporter.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      scheme: {{ .Values.serviceMonitor.scheme | default "http" | quote }}
      {{- with .Values.serviceMonitor.interval }}
      interval: {{ . | quote }}
      {{- end }}
      {{- with .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . | quote }}
      {{- end }}
{{- if .Values.serviceMonitor.relabelings }}
      relabelings:
{{ toYaml .Values.serviceMonitor.relabelings | nindent 8 }}
{{- end }}
{{- if .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
{{ toYaml .Values.serviceMonitor.metricRelabelings | nindent 8 }}
{{- end }}
{{- end }}

