{{- if .Values.server }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default "multicloud-exporter" .Values.fullname }}-config
data:
  server.yaml: |
{{ toYaml .Values.server | nindent 4 }}
{{- end }}
