{{- if .Values.server }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default "multicloud-exporter" .Values.fullname }}-config
  labels: {{- include "multicloud-exporter.labels" . | nindent 4 }}
data:
  server.yaml: |
    server:
{{ toYaml .Values.server | nindent 6 }}
{{- end }}
