{{- if .Values.server }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "multicloud-exporter.fullname" . }}-config
data:
  server.yaml: |
{{ toYaml .Values.server | nindent 4 }}
{{- end }}
