accounts:
  aliyun:
    - account_id: ""
      access_key_id: ""
      access_key_secret: ""
      regions: ["*"] # 采集所有区域
      resources:
        - bwp
        - lb
    - account_id: ""
      access_key_id: ""
      access_key_secret: ""
      regions: ["*"]
      resources:
        - bwp
        - lb
  tencent:
    - account_id: ""
      access_key_id: ""
      access_key_secret: ""
      regions: ["*"] # 采集所有区域
      resources:
        - bwp
        # - lb
