products:
  # mapping prefix -> local products filename by provider
  s3:
    aliyun: oss
    tencent: cos
    aws: s3
  clb:
    aliyun: clb
    tencent: clb
    aws: clb
  bwp:
    aliyun: cbwp
    tencent: bwp
  alb:
    aliyun: alb
    aws: alb
  nlb:
    aliyun: nlb
    aws: nlb
  gwlb:
    aliyun: gwlb
    tencent: gwlb
    aws: gwlb
