products:
  aliyun:
    - namespace: acs_ecs_dashboard
      period: 60
      metric_info:
        - metric_list:
          - AdvanceCredit
          - BurstCredit
          - CPUUtilization
          - ConnectionUtilization
          - DiskIOQueueSize
          - DiskReadBPS
          - DiskReadBPSUtilization
          - DiskReadIOPS
          - DiskReadIOPSUtilization
          - DiskReadWriteBPSBurstUtilization
          - DiskReadWriteBPSUtilization
          - DiskReadWriteIOPSBurstUtilization
          - DiskReadWriteIOPSUtilization
          - DiskWriteBPS
          - DiskWriteBPSUtilization
          - DiskWriteIOPS
          - DiskWriteIOPSUtilization
          - GroupCPUUtilization
          - GroupDiskReadBPS
          - GroupDiskReadIOPS
          - GroupDiskWriteBPS
          - GroupDiskWriteIOPS
          - GroupInternetInRate
          - GroupInternetOutRate
          - GroupIntranetInRate
          - GroupIntranetOutRate
          - GroupVPC_PublicIP_InternetInRate
          - GroupVPC_PublicIP_InternetOutRate
          - Groupnetworkin_packages
          - Groupnetworkin_rate
          - Groupnetworkout_packages
          - Groupnetworkout_rate
          - Groupvm.CPUUtilization
          - Groupvm.DiskIORead
          - Groupvm.DiskIOWrite
          - Groupvm.DiskReadBPS
          - Groupvm.DiskReadIOPS
          - Groupvm.DiskUtilization
          - Groupvm.DiskWriteIOPS
          - Groupvm.LoadAverage
          - Groupvm.MemoryUtilization
          - Groupvm.TcpConnection
          - InstanceMemorySize
          - InstancevCPUNum
          - InternetIn
          - InternetInRate
          - InternetOut
          - InternetOutRate
          - InternetOutRate_Percent
          - IntranetIn
          - IntranetInRate
          - IntranetInRateBurstUtilization
          - IntranetInRateUtilization
          - IntranetOut
          - IntranetOutRate
          - IntranetOutRateBurstUtilization
          - IntranetOutRateUtilization
          - NotpaidSurplusCredit
          - OcnNobufErrPacketsInstance
          - OcnNobufErrPacketsNetCard
          - RegionInstanceMemorySize
          - RegionInstanceNum
          - RegionInstancevCPUNum
          - StatusCheck
          - StatusCheckIns
          - StatusCheckSys
          - SysOM_IOMonDisks_await_iostatIndicator
          - SysOM_IOMonDisks_bps_iostatIndicator
          - SysOM_IOMonDisks_ioburstCnt_exception
          - SysOM_IOMonDisks_iodelayCnt_exception
          - SysOM_IOMonDisks_iohangCnt_exception
          - SysOM_IOMonDisks_iops_iostatIndicator
          - SysOM_IOMonDisks_qusize_iostatIndicator
          - SysOM_IOMonDisks_util_iostatIndicator
          - SysOM_diskLatency_busy
          - SysOM_diskLatency_rwait
          - SysOM_diskLatency_wwait
          - SysOM_dnsHist_100ms
          - SysOM_dnsHist_10ms
          - SysOM_dnsHist_1s
          - SysOM_dnsHist_1ss
          - SysOM_dnsHist_1sx
          - SysOM_dnsHist_500ms
          - SysOM_httpHist_100ms
          - SysOM_httpHist_10ms
          - SysOM_httpHist_1s
          - SysOM_httpHist_1ss
          - SysOM_httpHist_1sx
          - SysOM_httpHist_500ms
          - SysOM_memMonAlloc_pagefault
          - SysOM_memMonAlloc_thpCollapseAlloc
          - SysOM_memMonAlloc_thpCollapseAllocFailed
          - SysOM_memMonAlloc_thpFaultAlloc
          - SysOM_memMonAlloc_thpFaultFallback
          - SysOM_memMonBuddyinfo_normal0
          - SysOM_memMonBuddyinfo_normal1
          - SysOM_memMonBuddyinfo_normal10
          - SysOM_memMonBuddyinfo_normal2
          - SysOM_memMonBuddyinfo_normal3
          - SysOM_memMonBuddyinfo_normal4
          - SysOM_memMonBuddyinfo_normal5
          - SysOM_memMonBuddyinfo_normal6
          - SysOM_memMonBuddyinfo_normal7
          - SysOM_memMonBuddyinfo_normal8
          - SysOM_memMonBuddyinfo_normal9
          - SysOM_memMonInfo_SReclaimable
          - SysOM_memMonInfo_SUnreclaim
          - SysOM_memMonInfo_allocPageUsed
          - SysOM_memMonInfo_buff
          - SysOM_memMonInfo_cache
          - SysOM_memMonInfo_free
          - SysOM_memMonInfo_total
          - SysOM_memMonInfo_used
          - SysOM_memMonInfo_util
          - SysOM_memMonReclaim_allocstall
          - SysOM_memMonReclaim_compactStall
          - SysOM_memMonReclaim_compactSuccess
          - SysOM_memMonReclaim_oomKill
          - SysOM_memMonReclaim_pgscanDirect
          - SysOM_memMonReclaim_pgscanKswapd
          - SysOM_memMonReclaim_swpin
          - SysOM_memMonReclaim_swpout
          - SysOM_netHist_ms10
          - SysOM_netHist_ms100
          - SysOM_netHist_s1
          - SysOM_netHist_so
          - SysOM_netRetransC_rto
          - SysOM_netRetransC_sys
          - SysOM_packetStatus_abort
          - SysOM_packetStatus_drop
          - SysOM_packetStatus_err
          - SysOM_packetStatus_fail
          - SysOM_packetStatus_overflow
          - SysOM_packetStatus_paws
          - SysOM_packetStatus_retrans
          - SysOM_pingtrace_lRxKern
          - SysOM_pingtrace_lRxMergedKern
          - SysOM_pingtrace_lRxTaskQueue
          - SysOM_pingtrace_lRxTaskWaking
          - SysOM_pingtrace_lTxKern
          - SysOM_pingtrace_lTxMergedKern
          - SysOM_pingtrace_lTxQdisc
          - SysOM_pingtrace_link
          - SysOM_pingtrace_total
          - SysOM_redisHist_100ms
          - SysOM_redisHist_10ms
          - SysOM_redisHist_1s
          - SysOM_redisHist_1ss
          - SysOM_redisHist_1sx
          - SysOM_redisHist_500ms
          - SysOM_schedMoni_delay
          - SysOM_schedMoni_forked
          - SysOM_schedMoni_hirq
          - SysOM_schedMoni_load1
          - SysOM_schedMoni_load15
          - SysOM_schedMoni_load5
          - SysOM_schedMoni_nrIo
          - SysOM_schedMoni_nrRun
          - SysOM_schedMoni_pcnt
          - SysOM_schedMoni_plit
          - SysOM_schedMoni_runq
          - SysOM_schedMoni_sirq
          - SysOM_schedMoni_sys
          - SysOM_schedMoni_user
          - SysOM_schedMoni_util
          - SysOM_schedMoni_wait
          - SysOM_schedMoniirqoff_dltnum
          - SysOM_schedMoniirqoff_dlttm
          - SysOM_schedMoniirqoff_lt100ms
          - SysOM_schedMoniirqoff_lt10ms
          - SysOM_schedMoniirqoff_lt1s
          - SysOM_schedMoniirqoff_lt500ms
          - SysOM_schedMoniirqoff_lt50ms
          - SysOM_schedMoniirqoff_mts
          - SysOM_schedMoninoschd_dltnum
          - SysOM_schedMoninoschd_dlttm
          - SysOM_schedMoninoschd_lt100ms
          - SysOM_schedMoninoschd_lt10ms
          - SysOM_schedMoninoschd_lt1s
          - SysOM_schedMoninoschd_lt500ms
          - SysOM_schedMoninoschd_lt50ms
          - SysOM_schedMoninoschd_mts
          - SysOM_systemHealthFreq_hung
          - SysOM_systemHealthFreq_io
          - SysOM_systemHealthFreq_mem
          - SysOM_systemHealthFreq_net
          - SysOM_systemHealthFreq_wait
          - SysOM_systemHealthLog_hung
          - SysOM_systemHealthLog_io
          - SysOM_systemHealthLog_mem
          - SysOM_systemHealthLog_net
          - SysOM_systemHealthLog_wait
          - SysOM_systemHealth_hung
          - SysOM_systemHealth_io
          - SysOM_systemHealth_mem
          - SysOM_systemHealth_net
          - SysOM_systemHealth_wait
          - SysOM_tcpRetransSegs_fastRetrans
          - SysOM_tcpRetransSegs_lostRetransmit
          - SysOM_tcpRetransSegs_retransFail
          - SysOM_tcpRetransSegs_retransSegs
          - SysOM_tcpRetransSegs_slowStartRetrans
          - SysOM_tcpRetransSegs_synRetrans
          - SystemFileDescriptorUtlization
          - TotalCredit
          - TotalInstanceMemorySize
          - TotalInstanceNum
          - TotalInstancevCPUNum
          - VPC_PublicIP_InternetInRate
          - VPC_PublicIP_InternetInRate_Percent
          - VPC_PublicIP_InternetOutRate
          - VPC_PublicIP_InternetOutRate_Percent
          - aep_bw_read
          - aep_bw_write
          - aep_iops_read
          - aep_iops_write
          - concurrentConnections
          - cpu_cores
          - cpu_idle
          - cpu_other
          - cpu_system
          - cpu_total
          - cpu_user
          - cpu_wait
          - disk_readbytes
          - disk_readiops
          - disk_writebytes
          - disk_writeiops
          - diskusage_avail
          - diskusage_free
          - diskusage_total
          - diskusage_used
          - diskusage_utilization
          - eip_InternetInRate
          - eip_InternetOutRate
          - eri_active_qp_num
          - fs_inodeutilization
          - gpu_decoder_utilization
          - gpu_encoder_utilization
          - gpu_gpu_temperature
          - gpu_gpu_usedutilization
          - gpu_memory_freespace
          - gpu_memory_freeutilization
          - gpu_memory_usedspace
          - gpu_memory_usedutilization
          - gpu_power_readings_power_draw
          - group_gpu_decoder_utilization
          - group_gpu_encoder_utilization
          - group_gpu_gpu_temperature
          - group_gpu_gpu_usedutilization
          - group_gpu_memory_freespace
          - group_gpu_memory_freeutilization
          - group_gpu_memory_usedspace
          - group_gpu_memory_usedutilization
          - group_gpu_power_readings_power_draw
          - instance_gpu_decoder_utilization
          - instance_gpu_encoder_utilization
          - instance_gpu_gpu_temperature
          - instance_gpu_gpu_usedutilization
          - instance_gpu_memory_freespace
          - instance_gpu_memory_freeutilization
          - instance_gpu_memory_usedspace
          - instance_gpu_memory_usedutilization
          - instance_gpu_power_readings_power_draw
          - load_15m
          - load_1m
          - load_5m
          - load_per_core_15m
          - load_per_core_1m
          - load_per_core_5m
          - memory_actualusedspace
          - memory_freespace
          - memory_freeutilization
          - memory_totalspace
          - memory_usedspace
          - memory_usedutilization
          - net_tcpconnection
          - networkcredit_limit_overflow_errorpackets
          - networkin_droppackages_percent
          - networkin_errorpackages
          - networkin_packages
          - networkin_rate
          - networkout_droppackages_percent
          - networkout_errorpackages
          - networkout_packages
          - networkout_rate
          - packetInDropRates
          - packetOutDropRates
          - process.cpu
          - process.expend
          - process.memory
          - process.number
          - process.openfile
          - rx_eri_bw_bps
          - rx_eri_pkt_pps
          - tx_eri_bw_bps
          - tx_eri_pkt_pps
          - vm.CPUUtilization
          - vm.DiskIORead
          - vm.DiskIOWrite
          - vm.DiskIusedUtilization
          - vm.DiskUtilization
          - vm.LoadAverage
          - vm.MemoryUtilization
          - vm.Process.number
          - vm.ProcessCount
          - vm.TcpCount
    - namespace: acs_bandwidth_package
      period: 60
      metric_info:
        - metric_list:
          - in_bandwidth_utilization
          - out_bandwidth_utilization
          - net_rx.rate
          - net_tx.rate
          - net_rx.Pkgs
          - net_tx.Pkgs
          - in_ratelimit_drop_pps
          - out_ratelimit_drop_pps
    - namespace: acs_slb_dashboard
      period: 60
      metric_info:
        - metric_list:
				  - ActiveConnection # 监听每秒活跃连接数
				  - DropConnection # 监听每秒丢失连接数
				  - DropPacketRX # 监听每秒丢失入包数
				  - DropPacketTX # 监听每秒丢失出包数
				  - DropTrafficRX # 监听每秒丢失入bit数
				  - DropTrafficTX # 监听每秒丢失出bit数
				  - GroupActiveConnection # 分组活跃连接数
				  - GroupNewConnection # 分组新建连接数
				  - GroupTotalTrafficRX # 分组流入带宽合计
				  - GroupTotalTrafficTX # 分组流出带宽合计
				  - GroupTrafficRX # 分组流入带宽(不推荐)
				  - GroupTrafficTX # 分组流出带宽(不推荐)
				  - GroupUnhealthyServerCount # 分组后端异常ECS实例个数
				  - HealthyServerCountWithRule # 七层转发规则后端健康ECS实例个数
				  - HeathyServerCount # 健康检查后端健康ECS实例个数
				  - InactiveConnection # 监听非活跃连接数
				  - InstanceActiveConnection # 实例每秒活跃连接数
				  - InstanceDropConnection # 实例每秒丢失连接数
				  - InstanceDropPacketRX # 实例每秒丢失入包数
				  - InstanceDropPacketTX # 实例每秒丢失出包数
				  - InstanceDropTrafficRX # 实例每秒丢失入bit数
				  - InstanceDropTrafficTX # 实例每秒丢失出bit数
				  - InstanceInactiveConnection # 实例每秒非活跃连接数
				  - InstanceMaxConnection # 实例每秒最大并发连接数
				  - InstanceMaxConnectionUtilization # 实例最大连接数使用率
				  - InstanceNewConnection # 实例每秒新建连接数
				  - InstanceNewConnectionUtilization # 实例新建连接数使用率
				  - InstancePacketRX # 实例每秒入包数
				  - InstancePacketTX # 实例每秒出包数
				  - InstanceQps # 七层实例QPS
				  - InstanceQpsUtilization # 七层实例QPS使用率
				  - InstanceRt # 七层实例RT
				  - InstanceStatusCode2xx # 七层实例每秒状态码2XX数量
				  - InstanceStatusCode3xx # 七层实例每秒状态码3XX数量
				  - InstanceStatusCode4xx # 七层实例每秒状态码4XX数量\t
				  - InstanceStatusCode5xx # 七层实例每秒状态码5XX数量
				  - InstanceStatusCodeOther # 七层实例每秒其它状态码数量
				  - InstanceTrafficRX # 实例每秒入bit数
				  - InstanceTrafficRXUtilization # 实例网络流入带宽使用率
				  - InstanceTrafficTX # 实例每秒出bit数
				  - InstanceTrafficTXUtilization # 实例网络流出带宽使用率
				  - InstanceUpstreamCode4xx # 七层实例每秒UpstreamCode4xx数量
				  - InstanceUpstreamCode5xx # 七层实例每秒UpstreamCode5xx数量
				  - InstanceUpstreamRt # 七层实例UpstreamRt
				  - MaxConnection # 监听每秒最大连接数
				  - NewConnection # 监听新建连接数
				  - PacketRX # 监听每秒流入数据包数
				  - PacketTX # 监听每秒流出数据包数
				  - Qps # 七层监听QPS
				  - Rt # 七层监听RT
				  - StatusCode2xx # 七层监听每秒状态码2XX数量\t
				  - StatusCode3xx # 七层监听每秒状态码3XX数量
				  - StatusCode4xx # 七层监听每秒状态码4XX数量
				  - StatusCode5xx # 七层监听每秒状态码5XX数量
				  - StatusCodeOther # 七层监听每秒其它状态码数量
				  - TrafficRXNew # 监听流入带宽
				  - TrafficTXNew # 监听流出带宽
				  - UnhealthyServerCount # 健康检查后端异常ECS实例个数
				  - UnhealthyServerCountWithRule # 七层转发规则后端异常ECS实例个数
				  - UpstreamCode4xx # 七层监听每秒UpstreamCode4xx数量
				  - UpstreamCode5xx # 七层监听每秒UpstreamCode5xx数量
				  - UpstreamRt # 七层监听UpstreamRt
  huawei: []
  tencent:
    - namespace: QCE/BWP
      period: 60
      metric_info:
        - metric_list:
          - InPkg # 共享带宽包入包量 count/s
          - InTraffic # 共享带宽包入带宽 Mbps
          - IntrafficBwpRatio # 带宽包入带宽利用率 %
          - OutPkg # 共享带宽包出包量 count/s
          - OutTraffic # 共享带宽包出带宽 Mbps
          - OuttrafficBwpRatio # 带宽包出带宽利用率 %
