products:
    tencent:
        - namespace: QCE/LB
          period: null
          auto_discover: false
          metric_info: []
        - namespace: QCE/BWP
          period: null
          auto_discover: false
          metric_info: []
        - namespace: QCE/COS
          period: null
          auto_discover: false
          metric_info: []
